# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install KickAss if needed
        run: |
          set -e
          cd ${{ runner.workspace }}
          if ! [ -f KickAss.jar ] ;then
            echo "Installing KickAss"
            EC = $(curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" -X GET http://theweb.dk/KickAssembler/KickAssembler.zip --output KickAssembler.zip)
            # we need to check the error code and weirdly enough github actions only supports exit code of size u8
            if [ $ EC -ne 200 ] ; then
              echo "Curl request ended with errorcode $EC"
              exit 1
            fi
            unzip -o KickAssembler.zip  
          else
            echo "Already installed proceeding."
          fi
      
      - name: Build asm
        run: | 
          set -e
          java -jar ${{ runner.workspace}}/KickAss.jar $GITHUB_WORKSPACE/main.asm -odir ${{runner.workspace}}/build -o ${{ runner.workspace}}/build/main.prg

      ## upload the artefacts to the pipeline
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact' 
          name: c64_lessons
          path: ${{ runner.workspace}}/build/*
          if-no-files-found: error
          retention-days: 1

      - name: CleanUP
        run: |           
          rm -rf ${{ runner.workspace}}/build
          
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      ## download the artefacts from the pipeline
      - uses: actions/download-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact' 
          name: c64_lessons
          path: ${{ runner.workspace}}/artefact                    

      - name: Deploy to C64
        run: |
          EC = $(curl -H "Content-Type multipart/form-data" -F  "file=@${{runner.workspace}}/artefact/main.prg" "http://192.168.178.156/v1/runners:run_prg")
          # We need this because github actions only uses unsigned 8 bit exit codes as errors
          if [ $ EC -ne 200 ] ; then
            echo "Curl request ended with errorcode $EC"
            exit 1
          fi

      - name: CleanUP
        run: |           
          rm -rf ${{ runner.workspace}}/artefact
          
